### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by timaschew** [js2coffee/js2coffee-redux#1]
yeah the first issue :smile_cat: 

> - Source maps.

I don't understand why you need source maps for js2coffee? 

> These should be made configurable:
> - Toggle implicit returns.

I don't understand why you want to be configurable, you can't check if you need to return an undefined, because you need to understand the intention of the function and its usage. Or what do you mean with **toggle implicit returns**?
see https://github.com/js2coffee/js2coffee/issues/48#issuecomment-1352463 /cc @michaelficarra

> - Toggle trailing commas in multiline arrays/objects.

There is a case of an object with nested arrays which which need a comma, you cannot avoid it, I know it, because this was my first pull request for js2coffee and I ran into this case.

> - Postfix if statements will not be supported by default

what is the reason for that? is it too complex and cause issues like: https://github.com/js2coffee/js2coffee/issues/213 ?

**Comment by rstacruz** [comment]
> Source maps

Because (1) it's not that hard, and (2) it'd be nice to have a web editor that will highlight the part that's compiled. Imagine if you typed `function x() { return y; }` on the left pane, and put your cursor on `y`, and have the compiled CoffeeScript part (on the right) underlined where `y` was compiled to.

> Toggle implicit returns

Hm, I think the better wording would be more like "toggle the adding of an extra return for functions that don't return anything explicitly". This will of course break compatibility when it's turned off, but some people are less concerned about that for small snippets that they just want to learn from how their JS would be written in CoffeeScript.

> Postfix if statements will not be supported by default

Yes! Precisely because of js2coffee/js2coffee#213. Anyway, since there would be more configurability, it should be possible to have this behavior returned as an optional flag.

The key here is that the "default" js2coffee should work in a "compatibility first" mode: that is, avoiding constructs that may make code more elegant, but aren't guaranteed to work 100%. Trailing commas and postfix if statements are two of those things that can cause incompatibilities in edge cases. Users should be given an option to turn them on if they want (like `--postfix-if` and `js2coffee('if(a)b()', { postfixIf: true })`), but things that can't guarantee 100% compatibility should be disabled by default.

Hope this explains it. :) Thoughts?

**Comment by timaschew** [comment]
> Source maps

Okay, sounds nice :)

> Toggle implicit returns

-1 for 'not guaranteed to work'

```
function x() {
  return 'foo'
}
```

can be compiled into 

```
x = ->
  "foo"
```

and here it makes sense to enable implicit returns

but you should compile this:

```
function x() {
  doSomething()
}
```

always into 

```
x = ->
  doSomething()
  return
```

event if you disable implicit returns

the same for trailing commas and  js2coffee/js2coffee#213 (which should be easy to fix)
I'm just against to produce broken coffee code.

**Comment by rstacruz** [comment]
Ideally, the mission is:
- js2coffee will produce compatible code to the best of its ability.
- you can make your code more elegant with optional flags, but you have to understand the consequences.

---

> Returns

With this code:

``` js
function run() { a(); }
```

Js2coffee produces:

``` coffee
run = ->
  a()
  return
```

...but i was hoping to make this be optionally compile into this below, perhaps with `--no-implicit-returns`. This _can_ break compatibility, but since it's an optional flag, the assumption is that the user will already be aware of its consequences.

``` js
run = ->
  a()
```

---

> Trailing commas

This array:

``` js
[ 2, 3 ]
```

Turns into this:

``` coffee
[
  2
  3
]
```

Which probably should be:

``` coffee
[
  2,
  3
]
```

...this is mostly a stylistic consideration though, I'm not sure which is better to go with.

**Comment by timaschew** [comment]
> Trailing commas

Yeah this is fine, I was confused, I didn't mean commas, I meant curly braces for cases like this:

```
var root = [
    {k1: [[1],2]},
    {k2: [[1],2]},
]
```

I think you can always avoid commas, if you use multilines.

---

> This can break compatibility, but since it's an optional flag, the assumption is that the user will already be aware of its consequences.

Yeah I understand, but I'm -1 for it :)

**Comment by rstacruz** [comment]
Okay, makes sense :)

**Comment by timaschew** [comment]
> Yeah this is fine, I was confused, I didn't mean commas, I meant curly braces for cases like this:

I meant the mix of it: if you omit curly braces, you need commas, you cannot omit both:

you can see it if you remove the comma, the output become different

```
root = [
    x: [
      1
      2
    ]
  ,
    y: [
      3
      4
    ]
]
```

btw: @michaelficarra coffee-script-redux doesn't work with a comma here ;)

**Comment by pronebird** [comment]
For a starter,  would be awesome to split `js2coffee.coffee` on couple of files, it's really hard to navigate in this blob, but the code seems good.

**Comment by rstacruz** [comment]
Separated some of the lesser-important things into `lib/`, but now `js2coffee.coffee`'s grown even more haha.

**Comment by rstacruz** [comment]
Adding the extra `return` statement is now in — and there's no way to turn it off as @timeaschew's argued :)
